### ISSUE TITLE
to_info is not creating valid json

### ISSUE THREAD

**Issue by Razzeee** [fuzeman/trakt.py#6]
The dates seem to be datetime objects, would be nice if these could be strings.

Here is an example:
```
			{
				'plays': None,
				'collected_at': datetime.datetime(2014,
				5,
				18,
				23,
				12,
				10),
				'collected': 1,
				'watched': 0,
				'number': 19,
				'ids': {
					
				}
			},
```

**Comment by fuzeman** [comment]
Looking into this today as well.

**Comment by Razzeee** [comment]
@fuzeman 
that was my temp fix https://github.com/Razzeee/script.trakt/commit/34b58414639fa75b1dc20506e9bef56bfcdb1a3a
don't know know where watched_at is genereated

**Comment by fuzeman** [comment]
This has been fixed in https://github.com/fuzeman/trakt.py/commit/0a2a42d88fc8c407233fcd1b0436156b7cf5df68, timestamps are now returned as ISO 8601 strings (matches what the trakt API returns/accepts).

There is actually no references to `watched_at` in trakt.py, probably something that should be added...

-------

**Note:** I've renamed `to_info()` to `to_dict()`, the old method still exists but it just raises a deprecation warning now.

**Comment by Razzeee** [comment]
I'm getting to the point where I need watched_at and the trakt team is going to add it to the episode level in the next days (for the watched call)

**Comment by fuzeman** [comment]
Sounds good, ```watched_at``` will be helpful when I start redesigning a few components of syncing in https://github.com/trakt/Plex-Trakt-Scrobbler
